#pragma once

/**********************************************
* Author: Tao Wang  Copyright reserved
* Contact: tao.reiches@gmail.com
**********************************************/

enum BeCarryType
{
	BCT_BASE = 0,
	BCT_ITEM,
	BCT_BUFFER,
	BCT_SKILL,
	BCT_EQUIP,
	BCT_GENIUS,
	BCT_SUITING,
	BCT_LEVEL_STRENGTHEN_SUIT,

	BCT_NUM,
};

enum BeCarryFlag
{
	BCF_HAS_NORMAL_ATTR = (1 << 1),
	BCF_BUFFER_SHOW_LEVEL = (1 << 2),
};

enum BeNormalAttType
{
	NAT_ABS_ALL = 1,
	NAT_ABS_STR,
	NAT_ABS_AGI,
	NAT_ABS_INT,
	NAT_PLUS_STR,
	NAT_PLUS_AGI,
	NAT_PLUS_INT,
	NAT_ABS_MAX_HP,
	NAT_ABS_MAX_MP,
	NAT_ABS_REGEN_HP,
	NAT_PER_REGEN_HP,
	NAT_ABS_REGEN_MP,
	NAT_PER_REGEN_MP,
	NAT_ABS_ARMOR,
	NAT_PER_ARMOR,
	NAT_ABS_DAMAGE,
	NAT_PER_DAMAGE_BASE,
	NAT_PER_DAMAGE_ADD,
	NAT_PER_ATTACK_SPEED,

	NAT_BASE_MOVE_SPEED,
	NAT_ABS_MOVE_SPEED,
	NAT_PER_MOVE_SPEED,
	NAT_PER_DEMAGE,
	NAT_PER_BEDEMAGED,
	NAT_ABS_VISION_NIGHT,
	NAT_ABS_VISION_DAY,
	NAT_PER_VISION,

	NAT_ABS_MAGIC,
	NAT_PER_SKILLBLAST,
	NAT_SKILLBLAST_DAMAGEPER,

	NAT_BASE_ATTACK_CD,

	NAT_MAGIC_ARMOR,
	NAT_DEC_MAGIC_RESISTANCE,
	NAT_LEECH,
	NAT_INIT_MONEY,
	NAT_DEC_ARMOR,

	NAT_DEC_MPCOST,
	NAT_DEC_CDTIME,

	NAT_ABS_ENMITY_POINT,
	NAT_PER_DAMAGE_REDUCE,
	NAT_PER_AVOIDPHYSIC,
	NAT_REBOUND_SHORTRANGE,
	NAT_REBOUND_EJECT,
	NAT_PER_DAMAGE_SKILL,
	NAT_PER_ADDHP,

	NAT_PER_DEATH_AWARD,
	NAT_HP_UPPER_LIMIT_PER,
	NAT_MP_UPPER_LIMIT_PER,
	NAT_PET_SCALE,
	NAT_AWARD_ITEM,
	NAT_FUN_FIGHT,
	NAT_PRIMARY,
	NAT_ADD_SOLDIERS,
	NAD_ADD_FOOD,
	NAT_PER_REGEN_MAXHP,
	NAT_ADD_GLORY,
	NAT_PER_FASHUCHUANTOU,

	NAT_ATTACKSPEED_ADD,
	NAT_PER_CDTIME,
	NAT_PER_DEC_ARMOR,
	NAT_BAOJI,
	NAT_ABS_ATTACKRANGE,
	NAT_ABS_DECDAMAGE,
	NAT_PER_MAGIC,
	NAT_TOUGHNESS,
	NAT_MAGIC_LEECH,
	NAT_PER_MAGIC_ARMOR,
	NAT_PER_BASE_MAXHP,
	NAT_PER_BAOJI,
	NAT_PER_DEC_BAOJI,
	NAT_DEC_CDTIME_MAX,

	NAT_MAX_NUM,
};

class BeNormalAtt
{
public:
	BeNormalAtt(BeNormalAttType type, float value)
	{
		eType = type;
		fValue = value;
	}

	BeNormalAttType	eType;
	float			fValue;
};
