#pragma once

/**********************************************
* Author: Tao Wang  Copyright reserved
* Contact: tao.reiches@gmail.com
**********************************************/

enum BeTriggerEvent
{
	BTE_NULL = 0,

	BTE_INIT_SKILL_ATTR,

	BTE_LEARN_SPELL,
	BTE_SPELL_PREPARE,
	BTE_SPELL_CAST,
	BTE_SPELL_EFFECT,
	BTE_SPELL_FINISH,
	BTE_SPELL_CMDEND,
	BTE_SPELL_CLOSE,
	BTE_SPELL_XULI,

	BTE_SPELL_CASTEND,
	BTE_SPELL_EFFECTEND,

	BTE_UNIT_ADD_ITEMPRE,
	BTE_UNIT_ADD_ITEM,
	BTE_UNIT_PICKUP_ITEM,
	BTE_UNIT_DROP_ITEM,
	BTE_UNIT_USE_ITEMCAST,
	BTE_UNIT_USE_ITEM,
	BTE_UNIT_USEITEM_FINISH,
	BTE_UNIT_BUY_ITEM,
	BTE_UNIT_BUY_TOWN_ITEM,

	BTP_iMissionPlayer,
	BTP_iMissionID,

	BTE_UNIT_ATTACKED_PRE,
	BTE_UNIT_ATTACKED,
	BTE_UNIT_ATTACKED_NOTFIRST,
	BTE_UNIT_AFTERATTACKED,
	BTE_UNIT_SOUL_DEATH,
	BTE_UNIT_DEATH,
	BTE_UNIT_TIMEDEATH,
	BTE_UNIT_MORPH_CANCEL,
	BTE_UNIT_MORPH_CANCEL_AFTER,
	BTE_UNIT_DELUNIT,
	BTE_UNIT_ADDUNIT,
	BTE_UNIT_TARGET_CHANGED,
	BTE_SOLIDER_WALK_FORWARD,
	BTE_HERO_ATTACK,
	BTE_NOT_HERO_ATTACK,
	BTE_BUILDING_ATTACK,
	BTE_MONSTER_COME_BACK,
	BTE_MONSTER_ALARM,
	BTE_HERO_RELIVE,
	BTE_UNIT_LEVELUP,
	BTE_UNIT_PLAYERCMD,
	BTE_UNIT_HELP,

	BTE_UNIT_ADDBUFFER,
	BTE_UNIT_ADDBUFFER_AFTER,
	BTE_UNIT_DELBUFFER,
	BTE_UNIT_DELBUFFER_AFTER,

	BTE_BUFFER_ONPREATTACK,
	BTE_BUFFER_ONATTACK,
	BTE_BUFFER_ONPREDAMAGE,
	BTE_BUFFER_ONDAMAGE,
	BTE_BUFFER_ONPREBEDAMAGE,
	BTE_BUFFER_ONBEDAMAGE,
	BTE_BUFFER_ONDEAD,
	BTE_BUFFER_UPDATE,
	BTE_BUFFER_INVISIBLEBREAK,
	BTE_BUFFER_ONCDCOMPLETE,
	BTE_BUFFER_ONSPELL,
	BTE_BUFFER_ONKILL,
	BTE_BUFFER_ONDEAD_PRE,
	BTE_BUFFER_INVISIBLE_ENTER,

	BTE_SHIELD_BEDAMAGE,
	BTE_SHIELD_DELBUFFER,

	BTE_DOODAD_ADDBUFFER,
	BTE_DOODAD_DELBUFFER,

	BTE_SKILL_ONPREATTACK,
	BTE_SKILL_ONATTACK,
	BTE_SKILL_PREONDAMAGE,
	BTE_SKILL_ONDAMAGE,
	BTE_SKILL_ONPREBEDAMAGE,
	BTE_SKILL_ONBEDAMAGE,
	BTE_SKILL_ONDEAD,
	BTE_SKILL_UPDATE,
	BTE_SKILL_INVISIBLEREADY,
	BTE_SKILL_INVISIBLEBREAK,
	BTE_SKILL_ONCDCOMPLETE,
	BTE_SKILL_ONEFFECTARRIVE,
	BTE_SKILL_ONSPELL,
	BTE_SKILL_ONKILL,
	BTE_SKILL_SKIP_DEATH,

	BTE_SKILL_PILENUM,

	BTE_SKILL_AFTERBEDAMAGE,
	BTE_SKILL_AUTOUSE,
	BTE_UNIT_ADDUNITFLAG,
	BTE_UNIT_DELUNITFLAG,

	BTE_UNIT_ADDCARRYFLAG,
	BTE_UNIT_DELCARRYFLAG,

	BTE_EFFECT_ADD,
	BTE_EFFECT_ARRIVED,
	BTE_EFFECT_AFFECT,
	BTE_EFFECT_AFFECT_AFTER,
	BTE_EFFECT_DEL,

	BTE_SKILL_LEVEL_CHANGE,
	BTE_CHOOSE_DIFFICULTY,

	BTE_CHANGE_BATTLE_STATE,
	BTE_ATTACK_AVOIDED,

	BTE_MAX_NUM,
};

enum BeTrgParamID
{
	BTP_pkCarray = 0,
	BTP_iSkillOrgTypeID,
	BTP_iSkillTypeID,
	BTP_iSkillLevel,
	BTP_iSkillUsePlayer,
	BTP_iSpellTargetID,
	BTP_fSpellOrgPosX,
	BTP_fSpellOrgPosY,
	BTP_fSpellTargetPosX,
	BTP_fSpellTargetPosY,
	BTP_fSpellDirectPosX,
	BTP_fSpellDirectPosY,
	BTP_iAttackType,
	BTP_iFlag,
	BTP_iFlagPtr,
	BTP_iAttackerPlayer,
	BTP_iTargetID,
	BTP_iItemID,
	BTP_iItemTypeID,
	BTP_iItemOwnerPlayer,
	BTP_iTriggerItemID,
	BTP_iOtherID,
	BTP_iUnitFlag,
	BTP_iCarryFlag,
	BTP_fFloatData,
	BTP_iIntData,
	BTP_iIsLearnSkill,
	BTP_iOtherTrgInt,
	BTP_iTrgEventBy,

	BTP_pkTrgUnit,
	BTP_pkAttacker,
	BTP_pkTarget,
	BTP_pkSkill,
	BTP_pkBuffer,
	BTP_pkEffect,
	BTP_iItemPos,
	BTP_pfDamage,
	BTP_piSpellTargetID,
	BTP_fRawDamage,
	BTP_pkAttackAttr,
	BTP_pkMapItem,

	BTP_piPersistTime,
	BTP_piPersistDeltaTime,

	BTP_iTargetType,
	BTP_bFromImba,
	BTP_fDamageFace,

	BTP_MAX_NUM,
};
