#pragma once

/**********************************************
* Author: Tao Wang  Copyright reserved
* Contact: tao.reiches@gmail.com
**********************************************/

#include "TW_BitmaskEnum.h"

enum class TwUnitOutputFlag
{
    BSUDCF_NULL = 0,
    BSUDCF_TYPEID = 1 << 0,
    BSUDCF_POSX = 1 << 1,
    BSUDCF_FACE = 1 << 2,
    BSUDCF_CURHP = 1 << 3,
    BSUDCF_MAXHP = 1 << 4,
    BSUDCF_CURMP = 1 << 5,
    BSUDCF_MAXMP = 1 << 6,
    BSUDCF_ATTACKCD = 1 << 7,
    BSUDCF_SCALE = 1 << 8,
    BSUDCF_UNITLEVEL = 1 << 9,
    BSUDCF_ACTIONNAME = 1 << 10,
    BSUDCF_MOVESPEED = 1 << 12,
    BSUDCF_GUANKAFLAG = 1 << 13,
    BSUDCF_FLAG = 1 << 14,
    BSUDCF_OTHERFLAG = 1 << 15,
    BSUDCF_CARRYFLAG = 1 << 16,
    BSUDCF_PATHFINDER = 1 << 17,
    BSUDCF_PATHFINDERSUCESS = 1 << 18,
    BSUDCF_STOPPATHFIND = 1 << 19,
    BSUDCF_REGENHP = 1 << 20,
    BSUDCF_REGENMP = 1 << 21,
    BSUDCF_CAMP = 1 << 22,
    BSUDCF_BEDAMAGED = 1 << 23,
    BSUDCF_HEROLVLUP = 1 << 24,
    BSUDCF_RESET_POX = 1 << 25,
    BSUDCF_EXP = 1 << 27,
    BSUDCF_SHELD = 1 << 28,
    BSUDCF_GRASS = 1 << 29,
    BSUDCF_PLAYER = 1 << 30,

    BSUDCF_NEW_UNIT = BSUDCF_TYPEID | BSUDCF_POSX | BSUDCF_FACE | BSUDCF_CURHP | BSUDCF_MAXHP | BSUDCF_ATTACKCD | BSUDCF_SCALE
    | BSUDCF_UNITLEVEL | BSUDCF_ACTIONNAME | BSUDCF_MOVESPEED | BSUDCF_GUANKAFLAG | BSUDCF_FLAG | BSUDCF_OTHERFLAG | BSUDCF_CARRYFLAG
    | BSUDCF_PATHFINDER | BSUDCF_REGENHP | BSUDCF_REGENMP | BSUDCF_CAMP | BSUDCF_EXP | BSUDCF_SHELD | BSUDCF_GRASS | BSUDCF_PLAYER
    | BSUDCF_MAXMP | BSUDCF_CURMP,
};
ENABLE_BITMASK_OPERATORS(TwUnitOutputFlag)
