#pragma once

/**********************************************
* Author: Tao Wang  Copyright reserved
* Contact: tao.reiches@gmail.com
**********************************************/

enum BeUnitSearchFlag
{
	BUSF_CLASS_NORMAL = (1 << 0),
	BUSF_CLASS_HERO = (1 << 1),
	BUSF_CLASS_BUILDING = (1 << 2),

	BUSF_MOVETYPE_FLOOR = (1 << 3),
	BUSF_MOVETYPE_AIR = (1 << 4),

	BUSF_PROP_NONE = (1 << 5),
	BUSF_PROP_MACHINE = (1 << 6),
	BUSF_PROP_ORGANIC = (1 << 7),
	BUSF_PROP_GUARD = (1 << 8),
	BUSF_PROP_TREE = (1 << 9),

	BUSF_PROP_ANCIENT = (1 << 10),
	BUSF_WEAPON_MELEE = (1 << 11),
	BUSF_WEAPON_MISSILE = (1 << 12),

	BUSF_CAMP_ENEMY = (1 << 13),
	BUSF_CAMP_NATURE = (1 << 14),
	BUSF_CAMP_ALLY = (1 << 15),

	BUSF_VISION_OUTSIGHT = (1 << 16),

	BUSF_MAGIC_IMMUNITY = (1 << 17),

	BUSF_INVINCIBLE = (1 << 18),

	BUSF_SPELL_CASTER = (1 << 19),
	BUSF_SPELL_OTHER = (1 << 20),
};

enum BeSearchFlag
{
	BSF_NORMAL = BUSF_CLASS_NORMAL | BUSF_CLASS_HERO
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_MACHINE | BUSF_PROP_ORGANIC | BUSF_PROP_GUARD
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ENEMY | BUSF_CAMP_ALLY
	| BUSF_VISION_OUTSIGHT
	| BUSF_MAGIC_IMMUNITY
	| BUSF_SPELL_CASTER | BUSF_SPELL_OTHER,

	BSF_ATTACKABLE_ENEMY = BUSF_CLASS_NORMAL | BUSF_CLASS_HERO | BUSF_CLASS_BUILDING
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_MACHINE | BUSF_PROP_ORGANIC | BUSF_PROP_GUARD
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ENEMY
	| BUSF_MAGIC_IMMUNITY
	| BUSF_SPELL_OTHER,

	BSF_ENEMY = BUSF_CLASS_NORMAL | BUSF_CLASS_HERO | BUSF_CLASS_BUILDING
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_MACHINE | BUSF_PROP_ORGANIC | BUSF_PROP_GUARD
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ENEMY
	| BUSF_VISION_OUTSIGHT
	| BUSF_MAGIC_IMMUNITY
	| BUSF_SPELL_OTHER,

	BSF_SKILLTARGET_ENEMY = BUSF_CLASS_NORMAL | BUSF_CLASS_HERO
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_ORGANIC
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ENEMY
	| BUSF_VISION_OUTSIGHT
	| BUSF_SPELL_OTHER,

	BSF_SKILLEFFECT_ENEMY = BSF_SKILLTARGET_ENEMY
	| BUSF_VISION_OUTSIGHT,

	BSF_SKILLEFFECT_ALLY = BUSF_CLASS_NORMAL | BUSF_CLASS_HERO
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_ORGANIC
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ALLY
	| BUSF_VISION_OUTSIGHT
	| BUSF_SPELL_OTHER,


	BSF_AICONTROL_ALLY = BUSF_CLASS_NORMAL | BUSF_CLASS_BUILDING
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_ORGANIC | BUSF_PROP_MACHINE
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ALLY
	| BUSF_VISION_OUTSIGHT
	| BUSF_SPELL_OTHER,

	BSF_ALLY = BUSF_CLASS_NORMAL | BUSF_CLASS_HERO | BUSF_CLASS_BUILDING
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_MACHINE | BUSF_PROP_ORGANIC | BUSF_PROP_GUARD
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ALLY
	| BUSF_VISION_OUTSIGHT
	| BUSF_MAGIC_IMMUNITY
	| BUSF_SPELL_OTHER,

	BSF_ATTACKABLE_ENEMYHERO = BUSF_CLASS_HERO
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_MACHINE | BUSF_PROP_ORGANIC | BUSF_PROP_GUARD
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ENEMY
	| BUSF_MAGIC_IMMUNITY
	| BUSF_SPELL_OTHER,

	BSF_VISION_OUTSIGHT = BUSF_VISION_OUTSIGHT,

	BSF_ENEMY_HERO = BUSF_CLASS_HERO
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_MACHINE | BUSF_PROP_ORGANIC | BUSF_PROP_GUARD
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ENEMY
	| BUSF_VISION_OUTSIGHT
	| BUSF_MAGIC_IMMUNITY
	| BUSF_SPELL_OTHER,

	BSF_ENEMY_BUILDING = BUSF_CLASS_BUILDING
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_MACHINE | BUSF_PROP_ORGANIC | BUSF_PROP_GUARD
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ENEMY
	| BUSF_VISION_OUTSIGHT
	| BUSF_MAGIC_IMMUNITY
	| BUSF_SPELL_OTHER | BUSF_INVINCIBLE,

	BSF_HERO = BUSF_CLASS_HERO
	| BUSF_MOVETYPE_FLOOR | BUSF_MOVETYPE_AIR
	| BUSF_PROP_NONE | BUSF_PROP_MACHINE | BUSF_PROP_ORGANIC | BUSF_PROP_GUARD
	| BUSF_PROP_ANCIENT
	| BUSF_WEAPON_MELEE | BUSF_WEAPON_MISSILE
	| BUSF_CAMP_ENEMY | BUSF_CAMP_ALLY | BUSF_CAMP_NATURE
	| BUSF_VISION_OUTSIGHT
	| BUSF_MAGIC_IMMUNITY
	| BUSF_SPELL_OTHER,
};
